import type { ChamberProcessBeat } from "./componentProcesses";

function beat(
  stationId: string,
  id: string,
  label: string,
  startProgress: number,
  endProgress: number,
  cause: string,
  result: string,
  targetIds: readonly string[],
  auxiliarySceneKeys: readonly string[] = [],
): ChamberProcessBeat {
  return {
    id: `${stationId}:${id}`,
    stationId,
    label,
    startProgress,
    endProgress,
    cause,
    result,
    targetIds,
    auxiliarySceneKeys,
  };
}

export const LEARNING_EXPANSION_PROCESS_BEATS: ChamberProcessBeat[] = [
  beat(
    "target-comparison",
    "answer-arrives",
    "Bring the answer to the completed prediction",
    0.12,
    0.5,
    "The model must finish predicting before supervision identifies the correct next token.",
    "Target ID 5 arrives beside the fixed sixteen-class prediction distribution.",
    [
      "target-comparison:prediction-distribution",
      "target-comparison:answer-id",
    ],
    ["target-comparison-answer-flow"],
  ),
  beat(
    "target-comparison",
    "gather-correct-candidate",
    "Gather the probability at target ID 5",
    0.4,
    0.76,
    "Cross-entropy needs the probability assigned to the data target rather than the largest candidate by definition.",
    "The gather selects p[sat]=0.28 from the prediction row.",
    [
      "target-comparison:prediction-distribution",
      "target-comparison:answer-id",
      "target-comparison:gather-operation",
    ],
    ["target-comparison-answer-flow", "target-comparison-gather-flow"],
  ),
  beat(
    "target-comparison",
    "emit-correct-probabilities",
    "Complete the correct-probability batch",
    0.56,
    0.96,
    "The same gather must run for every one of the twelve supervised batch-position pairs.",
    "A [2,6] board of correct-token probabilities continues to cross-entropy.",
    [
      "target-comparison:gather-operation",
      "target-comparison:correct-probabilities",
    ],
    ["target-comparison-gather-flow"],
  ),

  beat(
    "output-backprop",
    "subtract-target",
    "Subtract the one-hot target",
    0.06,
    0.5,
    "Softmax cross-entropy differentiates each logit using the probability row and the aligned class label.",
    "The two operands produce p-one_hot(y) for the selected position.",
    [
      "output-backprop:probabilities",
      "output-backprop:one-hot-target",
      "output-backprop:difference",
    ],
    ["output-backprop-subtract-flow"],
  ),
  beat(
    "output-backprop",
    "apply-mean-reduction",
    "Scale by the twelve-position mean",
    0.36,
    0.74,
    "The scalar loss averaged all twelve supervised positions, so its derivative carries the same one-twelfth factor.",
    "The selected dL/dG row contains -0.06 at the target and +0.013333333 at competitor 6.",
    [
      "output-backprop:difference",
      "output-backprop:mean-logit-gradient",
    ],
    ["output-backprop-mean-reduction"],
  ),
  beat(
    "output-backprop",
    "fork-output-gradient",
    "Fork the output gradient",
    0.6,
    0.9,
    "The forward output matrix multiply depended on both H and W_vocab.",
    "The same dG is routed to the activation, vocabulary-weight, and vocabulary-bias derivative rules.",
    [
      "output-backprop:mean-logit-gradient",
      "output-backprop:gradient-fork",
      "output-backprop:hidden-state-gradient",
      "output-backprop:vocabulary-weight-gradient",
      "output-backprop:vocabulary-bias-gradient",
    ],
    ["output-backprop-fork-flow"],
  ),
  beat(
    "output-backprop",
    "emit-output-derivatives",
    "Emit tower and parameter gradients",
    0.78,
    0.99,
    "The activation derivative and both learned output-head parameter derivatives must finish before reverse traversal can continue.",
    "dH_final[2,6,8] enters the tower while dW_vocab[8,16] and db_vocab[16] join the parameter gradients.",
    [
      "output-backprop:gradient-fork",
      "output-backprop:hidden-state-gradient",
      "output-backprop:vocabulary-weight-gradient",
      "output-backprop:vocabulary-bias-gradient",
    ],
    ["output-backprop-fork-flow"],
  ),

  beat(
    "backprop-through-tower",
    "reverse-final-norm",
    "Reverse final layer normalization",
    0,
    0.2,
    "LN_f was the last internal transform that produced the final hidden states.",
    "The activation gradient enters block 1 and final-norm parameter gradients are deposited.",
    [
      "backprop-through-tower:incoming-gradient",
      "backprop-through-tower:final-norm-backward",
    ],
    ["backprop-final-norm-flow"],
  ),
  beat(
    "backprop-through-tower",
    "reverse-block-1-mlp",
    "Reverse block 1 MLP residual",
    0.16,
    0.38,
    "The upper block's MLP residual add is the next dependency encountered in reverse.",
    "Skip and transformed gradients merge after block 1 MLP and LN2 gradients are collected.",
    [
      "backprop-through-tower:final-norm-backward",
      "backprop-through-tower:block-1-mlp-backward",
    ],
    ["backprop-final-norm-flow", "backprop-block-1-mlp-flow"],
  ),
  beat(
    "backprop-through-tower",
    "reverse-block-1-attention",
    "Reverse block 1 attention residual",
    0.34,
    0.56,
    "The merged MLP input gradient now reaches the earlier attention residual in block 1.",
    "Block 1 attention and LN1 gradients are collected and the activation gradient reaches block 0.",
    [
      "backprop-through-tower:block-1-mlp-backward",
      "backprop-through-tower:block-1-attention-backward",
    ],
    ["backprop-block-1-mlp-flow", "backprop-block-1-attention-flow"],
  ),
  beat(
    "backprop-through-tower",
    "reverse-block-0-mlp",
    "Reverse block 0 MLP residual",
    0.52,
    0.74,
    "Backpropagation continues into the lower block in reverse forward order.",
    "Block 0 MLP and LN2 gradients accumulate before the residual branches merge.",
    [
      "backprop-through-tower:block-1-attention-backward",
      "backprop-through-tower:block-0-mlp-backward",
    ],
    ["backprop-block-1-attention-flow", "backprop-block-0-mlp-flow"],
  ),
  beat(
    "backprop-through-tower",
    "reverse-block-0-attention",
    "Reverse block 0 attention residual",
    0.7,
    0.91,
    "The first attention sublayer is the final Transformer dependency before H0.",
    "Block 0 attention and LN1 gradients accumulate and the merged gradient becomes dH0.",
    [
      "backprop-through-tower:block-0-mlp-backward",
      "backprop-through-tower:block-0-attention-backward",
    ],
    ["backprop-block-0-mlp-flow", "backprop-block-0-attention-flow"],
  ),
  beat(
    "backprop-through-tower",
    "handoff-to-embeddings",
    "Hand dH0 to embedding backward",
    0.8,
    0.99,
    "The tower chain rule is complete, but token and position lookup tables still require gradient accumulation.",
    "A [2,6,8] activation gradient exits toward embedding backward with all tower parameter gradients collected.",
    [
      "backprop-through-tower:block-0-attention-backward",
      "backprop-through-tower:embedding-gradient-output",
    ],
    ["backprop-block-0-attention-flow"],
  ),

  beat(
    "parameter-matrix",
    "locate-selected-cell",
    "Locate WQ cell [3,6]",
    0,
    0.3,
    "The weight, its gradient, and its optimizer state must all resolve to the same parameter address.",
    "Crosshairs isolate W_Q[3,6] and its stored value 0.0174.",
    [
      "parameter-matrix:wq-matrix",
      "parameter-matrix:selected-cell",
      "parameter-matrix:stored-weight",
    ],
  ),
  beat(
    "parameter-matrix",
    "stream-contributions",
    "Stream twelve gradient contributions",
    0.16,
    0.68,
    "The shared W_Q matrix was used at every one of the twelve batch-position examples.",
    "One local product per position arrives at the selected-cell gradient accumulator.",
    [
      "parameter-matrix:selected-cell",
      "parameter-matrix:gradient-contributions",
      "parameter-matrix:gradient-accumulator",
    ],
    ["parameter-matrix-contribution-flow"],
  ),
  beat(
    "parameter-matrix",
    "settle-gradient",
    "Settle the accumulated gradient",
    0.56,
    0.82,
    "AdamW requires one total derivative for each parameter rather than a separate update per token.",
    "The selected gradient register settles at g=-0.0031.",
    [
      "parameter-matrix:gradient-contributions",
      "parameter-matrix:gradient-accumulator",
      "parameter-matrix:settled-gradient",
    ],
    ["parameter-matrix-contribution-flow"],
  ),
  beat(
    "parameter-matrix",
    "hold-weight-locked",
    "Hold the parameter until optimization",
    0.7,
    0.94,
    "Differentiation computes gradients but is not authorized to mutate learned parameters.",
    "W_Q[3,6] remains 0.0174 while g=-0.0031 continues to AdamW.",
    [
      "parameter-matrix:wq-matrix",
      "parameter-matrix:stored-weight",
      "parameter-matrix:settled-gradient",
    ],
  ),

  beat(
    "adamw-state",
    "validate-inputs",
    "Assemble and validate optimizer inputs",
    0,
    0.22,
    "AdamW needs the current weight, gradient, moment state, step, and hyperparameters before it can compute a delta.",
    "The trace supplies g=-0.0031 at the AdamW entrance without exposing a pre-clipping norm, threshold, or clipping decision.",
    [
      "adamw-state:optimizer-inputs",
      "adamw-state:clip-check",
    ],
    ["adamw-moment-flow"],
  ),
  beat(
    "adamw-state",
    "update-moments",
    "Update first and second moments",
    0.1,
    0.36,
    "Adam tracks both signed direction and squared-gradient scale across optimizer steps.",
    "m1 becomes -0.00031 and v1 becomes 9.61e-9.",
    [
      "adamw-state:optimizer-inputs",
      "adamw-state:first-moment-lane",
      "adamw-state:second-moment-lane",
    ],
    ["adamw-moment-flow"],
  ),
  beat(
    "adamw-state",
    "bias-correct-moments",
    "Correct zero-initialization bias",
    0.26,
    0.54,
    "Moments initialized at zero are biased toward zero during early steps.",
    "Step-1 corrections produce m_hat=-0.0031 and v_hat=9.61e-6.",
    [
      "adamw-state:first-moment-lane",
      "adamw-state:second-moment-lane",
    ],
    ["adamw-moment-flow"],
  ),
  beat(
    "adamw-state",
    "normalize-gradient",
    "Normalize direction by recent scale",
    0.42,
    0.7,
    "The signed first moment must be scaled by the square root of the second moment before learning-rate application.",
    "The adaptive direction is -0.999996774.",
    [
      "adamw-state:first-moment-lane",
      "adamw-state:second-moment-lane",
      "adamw-state:normalized-gradient",
    ],
    ["adamw-moment-flow"],
  ),
  beat(
    "adamw-state",
    "combine-update-components",
    "Combine Adam and decoupled decay",
    0.6,
    0.99,
    "AdamW applies the adaptive gradient term and direct weight-decay term as separate influences.",
    "The two components sum to delta w=+0.000999822774.",
    [
      "adamw-state:normalized-gradient",
      "adamw-state:update-components",
      "adamw-state:delta-weight",
    ],
    ["adamw-update-flow"],
  ),

  beat(
    "weight-update",
    "bring-update-operands",
    "Bring the weight and delta together",
    0.08,
    0.52,
    "The optimizer has finished computing a signed delta, while the model still stores the old value.",
    "w_before=0.0174 and delta w=+0.000999822774 align at the update junction.",
    [
      "weight-update:stored-weight-before",
      "weight-update:delta-weight",
      "weight-update:scalar-addition",
    ],
    ["weight-update-operands-flow"],
  ),
  beat(
    "weight-update",
    "compute-updated-scalar",
    "Compute the replacement scalar",
    0.4,
    0.74,
    "A parameter changes only after its signed optimizer delta is added to the stored value.",
    "The addition produces w_after=0.018399822774.",
    [
      "weight-update:stored-weight-before",
      "weight-update:delta-weight",
      "weight-update:scalar-addition",
      "weight-update:updated-weight",
    ],
    ["weight-update-operands-flow"],
  ),
  beat(
    "weight-update",
    "write-selected-cell",
    "Write the selected matrix cell",
    0.62,
    0.94,
    "The computed scalar must be committed to its exact parameter address.",
    "W_Q[3,6] changes from 0.0174 to 0.018399822774.",
    [
      "weight-update:updated-weight",
      "weight-update:matrix-before",
      "weight-update:matrix-after",
    ],
    ["weight-update-write-flow"],
  ),
  beat(
    "weight-update",
    "commit-next-model-state",
    "Commit the updated matrix state",
    0.8,
    0.99,
    "The next forward pass must read the updated parameter store rather than the completed step's snapshot.",
    "The after-board becomes the W_Q state carried into theta1.",
    [
      "weight-update:matrix-before",
      "weight-update:matrix-after",
    ],
    ["weight-update-write-flow"],
  ),

  beat(
    "model-changed-next-step",
    "handoff-model-version",
    "Hand off theta0 to theta1",
    0.1,
    0.46,
    "The optimizer step has committed parameter deltas after the completed batch used theta0.",
    "The same architecture now carries updated parameter state theta1.",
    [
      "model-changed-next-step:old-parameter-state",
      "model-changed-next-step:updated-parameter-state",
    ],
    ["next-step-version-flow"],
  ),
  beat(
    "model-changed-next-step",
    "clear-gradients-keep-memory",
    "Clear gradients and retain Adam memory",
    0.38,
    0.68,
    "Temporary gradient accumulators belong to the completed batch, but Adam's moments are historical optimizer state.",
    "Gradient buffers drain while m1 and v1 persist for the next optimizer step.",
    [
      "model-changed-next-step:updated-parameter-state",
      "model-changed-next-step:gradient-buffer",
      "model-changed-next-step:optimizer-memory",
    ],
    ["next-step-version-flow"],
  ),
  beat(
    "model-changed-next-step",
    "admit-next-batch",
    "Admit a fresh batch",
    0.5,
    0.88,
    "Training continues with new examples after the model and optimizer states cross a clean iteration boundary.",
    "An unspecified [2,6] batch approaches theta1 with cleared gradient buffers.",
    [
      "model-changed-next-step:updated-parameter-state",
      "model-changed-next-step:gradient-buffer",
      "model-changed-next-step:optimizer-memory",
      "model-changed-next-step:next-batch",
    ],
    ["next-step-loop-gate"],
  ),
  beat(
    "model-changed-next-step",
    "restart-training-route",
    "Restart the ordered training route",
    0.74,
    0.99,
    "The next batch must perform a new forward, loss, backward, and update sequence using theta1.",
    "The training loop continues toward theta2; this chamber replay remains inspection-only.",
    [
      "model-changed-next-step:updated-parameter-state",
      "model-changed-next-step:next-batch",
      "model-changed-next-step:training-loop",
    ],
    ["next-step-loop-gate"],
  ),
];
