import type { ChamberProcessBeat } from "./componentProcesses";

function beat(
  stationId: string,
  id: string,
  label: string,
  startProgress: number,
  endProgress: number,
  cause: string,
  result: string,
  targetIds: readonly string[],
  auxiliarySceneKeys: readonly string[] = [],
): ChamberProcessBeat {
  return {
    id: `${stationId}:${id}`,
    stationId,
    label,
    startProgress,
    endProgress,
    cause,
    result,
    targetIds,
    auxiliarySceneKeys,
  };
}

export const EARLY_EXPANSION_PROCESS_BEATS = [
  beat(
    "token-stream-context",
    "source-arrival",
    "Bring the independent source rows to the cutter",
    0,
    0.28,
    "Prepared token rows must be positioned without mixing batch examples before a fixed context window can be selected.",
    "Both seven-token rows arrive in separate lanes beneath the shared cutter.",
    [
      "token-stream:source-rows",
      "token-stream:selection-clamps",
      "token-stream:window-cutter",
    ],
  ),
  beat(
    "token-stream-context",
    "lock-window",
    "Lock one T+1 window per row",
    0.14,
    0.52,
    "Six next-token input positions require a contiguous source span containing one additional answer token.",
    "Each clamp fixes a seven-token selection inside its own source row.",
    [
      "token-stream:source-rows",
      "token-stream:selection-clamps",
      "token-stream:window-cutter",
    ],
  ),
  beat(
    "token-stream-context",
    "extract-window",
    "Extract the clamped spans",
    0.34,
    0.84,
    "The selected spans must leave the longer token streams while retaining row identity and token order.",
    "The two isolated windows travel from their clamps onto separate output docks.",
    [
      "token-stream:source-rows",
      "token-stream:selection-clamps",
      "token-stream:output-docks",
      "token-stream:selected-windows",
    ],
  ),
  beat(
    "token-stream-context",
    "window-ready",
    "Present the selected windows",
    0.62,
    0.96,
    "The next chamber needs a validated two-by-seven source artifact before taking offset input and target slices.",
    "The docked T+1 windows are ready for shifted-target construction.",
    [
      "token-stream:output-docks",
      "token-stream:selected-windows",
    ],
  ),
  beat(
    "batch-shifted-targets",
    "duplicate-source",
    "Fork the source matrix into two views",
    0.08,
    0.34,
    "Inputs and labels come from different column ranges of the same source rows.",
    "Identical working views of S enter the X and Y routes.",
    [
      "batch-shift:source-matrix",
      "batch-shift:working-copies",
    ],
  ),
  beat(
    "batch-shifted-targets",
    "form-input-slice",
    "Keep columns 0 through 5 for X",
    0.26,
    0.7,
    "The model must see each prefix token but not the final token reserved as the last answer.",
    "Dropping the last source column produces the two-by-six model input batch X.",
    [
      "batch-shift:working-copies",
      "batch-shift:input-slice",
      "batch-shift:input-batch",
    ],
  ),
  beat(
    "batch-shifted-targets",
    "form-target-shift",
    "Keep columns 1 through 6 for Y",
    0.3,
    0.74,
    "Every X position needs the actual following source token as its categorical answer.",
    "Dropping the first source column and reindexing produces the aligned target batch Y.",
    [
      "batch-shift:working-copies",
      "batch-shift:target-shift",
      "batch-shift:target-batch",
    ],
  ),
  beat(
    "batch-shifted-targets",
    "pair-and-route",
    "Pair inputs with targets and separate their routes",
    0.52,
    0.99,
    "The model consumes X while cross-entropy later consumes Y, but their batch-position indices must remain paired.",
    "Twelve input IDs proceed to the model and twelve aligned target IDs proceed to scoring.",
    [
      "batch-shift:input-batch",
      "batch-shift:target-batch",
    ],
    ["batch-shift-pair-routing-flow"],
  ),
  beat(
    "transformer-tower",
    "block-0-transform",
    "Transform H0 through block 0",
    0,
    0.42,
    "Token-plus-position vectors need their first causal contextual and nonlinear update.",
    "Block 0 uses theta0 to convert H0 into the shape-preserving intermediate state H1.",
    ["tower:h0", "tower:block-0", "tower:h1"],
  ),
  beat(
    "transformer-tower",
    "block-1-transform",
    "Transform H1 through block 1",
    0.38,
    0.76,
    "A second independently parameterized block adds depth to the representation.",
    "Block 1 uses theta1 to convert H1 into the deepest residual-stream state H2.",
    ["tower:h1", "tower:block-1", "tower:h2"],
  ),
  beat(
    "transformer-tower",
    "final-normalization",
    "Normalize the top-block state",
    0.7,
    0.99,
    "The shared vocabulary projection needs consistently calibrated model-width vectors.",
    "Final LayerNorm converts H2 into H_final without changing its two-by-six-by-eight shape.",
    ["tower:h2", "tower:final-norm", "tower:final-output"],
  ),
  beat(
    "transformer-block",
    "attention-fork",
    "Fork H into attention and residual routes",
    0.04,
    0.3,
    "Causal attention must compute a contextual correction while the incoming residual stream remains available unchanged.",
    "H travels down the identity bypass while LN1 and multi-head attention produce update A.",
    [
      "transformer-block:input-h",
      "transformer-block:attention-residual",
      "transformer-block:attention-update",
    ],
  ),
  beat(
    "transformer-block",
    "attention-residual-add",
    "Add the attention update to H",
    0.24,
    0.54,
    "The contextual update has the same shape as H and can therefore refine it channel by channel.",
    "The first residual merge produces U=H+A.",
    [
      "transformer-block:attention-residual",
      "transformer-block:attention-update",
      "transformer-block:attention-output",
    ],
  ),
  beat(
    "transformer-block",
    "mlp-fork",
    "Fork U into MLP and residual routes",
    0.42,
    0.73,
    "The attention-updated state needs a nonlinear feature transform without losing the state already stored in U.",
    "U takes the identity bypass while LN2 and the shared 8-to-32-to-8 MLP produce F.",
    [
      "transformer-block:attention-output",
      "transformer-block:mlp-residual",
      "transformer-block:mlp-update",
    ],
  ),
  beat(
    "transformer-block",
    "mlp-residual-add",
    "Add the MLP update to U",
    0.67,
    0.99,
    "The position-wise feature update must rejoin the residual stream before the block can hand off its result.",
    "The second residual merge produces the completed block output H'=U+F.",
    [
      "transformer-block:mlp-residual",
      "transformer-block:mlp-update",
      "transformer-block:output-h",
    ],
  ),
] satisfies readonly ChamberProcessBeat[];
